server.port=8082
spring.application.name=ms-transacciones

# --- BASE DE DATOS (CLOUD READY) ---
spring.datasource.url=jdbc:postgresql://${DB_HOST:postgres-db-ecusol}:5432/db_ecusol_transacciones
spring.datasource.username=${DB_USER:postgres}
spring.datasource.password=${DB_PASSWORD:admin}
spring.datasource.driver-class-name=org.postgresql.Driver

# --- JPA ---
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

# --- SWAGGER ---
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

# --- CONEXIÓN ENTRE MICROSERVICIOS ---
# URLs dinámicas: En local usa http://nombre-contenedor:puerto
# En AWS usarás http://load-balancer-url
api.cuentas.url=${URL_MS_CUENTAS:http://ecusol-ms-cuentas:8083}
api.geo.url=${URL_MS_GEOGRAFIA:http://ecusol-ms-geografia:8081}
# (Opcional si vas a validar clientes en el futuro)
api.clientes.url=${URL_MS_CLIENTES:http://ecusol-ms-clientes:8084}

# --- SWITCH CENTRAL DIGICONECU ---
# Para pruebas locales usar: http://host.docker.internal:9081
# Para producción usar: http://34.44.123.236:9180
api.switch.url=${APP_SWITCH_URL:https://switch-interbank.ddns.net}
app.switch.url=${APP_SWITCH_URL:https://switch-interbank.ddns.net/api/switch/v1/transferir}
app.switch.apikey=${APP_SWITCH_APIKEY:public_key_ecusol_67890}
banco.codigo=${BANCO_CODIGO:ECUSOL_BK}